title: Mario Vozza
email: marvozza@gmail.com
description: "PhD in AI | Control Systems | Scientific Machine Learning"
baseurl: "" 
url: "https://mariovozza.github.io" 

theme: jekyll-theme-slate
plugins:
  - jekyll-feed
  - jekyll-seo-tag


# Menu principale
navigation:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Publications
    url: /publications/
  - title: Projects
    url: /projects/
  - title: Contact
    url: /contact/

# Google Fonts
google_fonts:
  - family: "Fira Sans"
  - family: "Fira Mono"

# Colori personalizzati (puoi mettere questo file in assets/css/custom.scss e importarlo)
sass:
  style: compressed
  load_paths:
    - _sass

# Personalizzazione CSS (crea _sass/_custom.scss e importalo nel main.scss)
